name: CI Pipeline

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry version "$(poetry version -s).$PATCH_NUMBER"
        poetry install -v
      env:
        PATCH_NUMBER: ${{ github.run_number }}
    - name: Build
      run: |
        poetry build
    - name: Lint
      run: |
        poetry run poe lint
    - name: Test
      run: |
        poetry run poe unit_test
    - name: Store build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/**
    - name: Build database
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        poetry run vulndb admin create
        poetry run vulndb nvd ingest
        poetry run vulndb osv ingest
        poetry run poe data_validation_test
    - name: Save Database to Cache
      id: cache-database-if-valid
      uses: actions/cache/save@v4
      with:
        key: ${{ github.head_ref }}.${{ github.sha }.db}
        path: |
          ~/.vulndb/vuln.db
    - name: Upload asset to Release
      uses: softprops/action-gh-release@v2
      if: github.ref == 'refs/heads/master'
      with:
        files: ~/.vulndb/vuln.db