name: CI Pipeline

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry version "$(poetry version -s).$PATCH_NUMBER"
        poetry install -v
      env:
        PATCH_NUMBER: ${{ github.run_number }}
    - name: Build
      run: |
        poetry build
    - name: Lint
      run: |
        poetry run poe lint
    - name: Test
      run: |
        poetry run poe unit_test
    - name: Restore database 
      uses: actions/cache/restore@v4
      with:
        key: ${{ github.head_ref }}.${{ github.sha }.db}
        path: |
          ~/.vulndb/vuln.db
    - name: Build database
      if: steps.restore-database.outputs.cache-hit
      run: |
        poetry run vulndb admin create
        poetry run vulndb nvd ingest --update
        poetry run vulndb osv ingest
        poetry run poe data_validation_test
    - name: Save Updated Database
      id: cache-database-if-valid
      uses: actions/cache/save@v4
      with:
        key: ${{ github.head_ref }}.${{ github.sha }.db}
        path: |
          ~/.vulndb/vuln.db