#
name: Create and publish a Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  workflow_dispatch:
  
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{secrets.DOCKERHUB_USERNAME}}/vulndb

      - name: Build&Push Basic Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/vulndb:basic
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile-basic

      - name: Build&Push Image with updated nvd data
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/vulndb:nvd
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile-update-nvd

      - name: Build&Push Image with updated nvd + osv
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/vulndb:nvd-osv, ${{secrets.DOCKERHUB_USERNAME}}/vunldb:latest
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile-basic
